### ISSUE TITLE
Loading a template modifies root slot definitions

### ISSUE THREAD

**Issue by pkalita-lbl** [cidgoh/DataHarmonizer#382]
When a template is loaded, this code merges together the root-level slot definition with the corresponding slot definition in a class's attribute list: https://github.com/cidgoh/DataHarmonizer/blob/c0010697950b82beb55b8770f393c2344dce46c7/lib/DataHarmonizer.js#L141-L149

The issue is that `Object.assign` modifies the "target" object (in this case `self.schema.slots[name]`).

To see the effect of this, consider this schema:

```yaml
id: http://example.org/test
name: test
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/

slots:
  s1:
    range: string

classes:
  C1:
    slots:
      - s1
    slot_usage:
      s1:
        required: true
        title: 'C1:s1'
  C2:
    slots:
      - s1
    slot_usage:
      s1:
        title: 'C2:s1'
```

When DataHarmonizer first loads the template for `C1`, the `C1:s1` column will be required as expected. However if the template is changed to `C2`, then the resulting column `C2:s1` will _also_ be marked as required, which is incorrect.
